LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= su.c

LOCAL_MODULE:= su

LOCAL_FORCE_STATIC_EXECUTABLE := true

LOCAL_STATIC_LIBRARIES := libc

LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE_TAGS := debug
ifeq (true,$(TARGET_PREFER_32_BIT_EXECUTABLES))
# We are doing a 32p build, force recovery to be 64bit
LOCAL_MULTILIB := 64
endif

include $(BUILD_EXECUTABLE)
