# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perfprofd_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='perfprofd_config.proto',
  package='android.perfprofd',
  syntax='proto2',
  serialized_pb=_b('\n\x16perfprofd_config.proto\x12\x11\x61ndroid.perfprofd\"\xf8\x03\n\x0fProfilingConfig\x12 \n\x18\x63ollection_interval_in_s\x18\x01 \x01(\r\x12\x16\n\x0euse_fixed_seed\x18\x02 \x01(\r\x12\x1c\n\x14main_loop_iterations\x18\x03 \x01(\r\x12\x1d\n\x15\x64\x65stination_directory\x18\x04 \x01(\t\x12\x18\n\x10\x63onfig_directory\x18\x05 \x01(\t\x12\x11\n\tperf_path\x18\x06 \x01(\t\x12\x17\n\x0fsampling_period\x18\x07 \x01(\r\x12\x1c\n\x14sample_duration_in_s\x18\x08 \x01(\r\x12\x18\n\x10only_debug_build\x18\t \x01(\x08\x12\x15\n\rhardwire_cpus\x18\n \x01(\x08\x12\'\n\x1fhardwire_cpus_max_duration_in_s\x18\x0b \x01(\r\x12 \n\x18max_unprocessed_profiles\x18\x0c \x01(\r\x12\x15\n\rstack_profile\x18\r \x01(\x08\x12\x1f\n\x17\x63ollect_cpu_utilization\x18\x0e \x01(\x08\x12\x1e\n\x16\x63ollect_charging_state\x18\x0f \x01(\x08\x12\x17\n\x0f\x63ollect_booting\x18\x10 \x01(\x08\x12\x1d\n\x15\x63ollect_camera_active\x18\x11 \x01(\x08\x42\x15\n\x11\x61ndroid.perfprofdH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROFILINGCONFIG = _descriptor.Descriptor(
  name='ProfilingConfig',
  full_name='android.perfprofd.ProfilingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collection_interval_in_s', full_name='android.perfprofd.ProfilingConfig.collection_interval_in_s', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_fixed_seed', full_name='android.perfprofd.ProfilingConfig.use_fixed_seed', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='main_loop_iterations', full_name='android.perfprofd.ProfilingConfig.main_loop_iterations', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destination_directory', full_name='android.perfprofd.ProfilingConfig.destination_directory', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_directory', full_name='android.perfprofd.ProfilingConfig.config_directory', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='perf_path', full_name='android.perfprofd.ProfilingConfig.perf_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampling_period', full_name='android.perfprofd.ProfilingConfig.sampling_period', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_duration_in_s', full_name='android.perfprofd.ProfilingConfig.sample_duration_in_s', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='only_debug_build', full_name='android.perfprofd.ProfilingConfig.only_debug_build', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardwire_cpus', full_name='android.perfprofd.ProfilingConfig.hardwire_cpus', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardwire_cpus_max_duration_in_s', full_name='android.perfprofd.ProfilingConfig.hardwire_cpus_max_duration_in_s', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_unprocessed_profiles', full_name='android.perfprofd.ProfilingConfig.max_unprocessed_profiles', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack_profile', full_name='android.perfprofd.ProfilingConfig.stack_profile', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_cpu_utilization', full_name='android.perfprofd.ProfilingConfig.collect_cpu_utilization', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_charging_state', full_name='android.perfprofd.ProfilingConfig.collect_charging_state', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_booting', full_name='android.perfprofd.ProfilingConfig.collect_booting', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_camera_active', full_name='android.perfprofd.ProfilingConfig.collect_camera_active', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=550,
)

DESCRIPTOR.message_types_by_name['ProfilingConfig'] = _PROFILINGCONFIG

ProfilingConfig = _reflection.GeneratedProtocolMessageType('ProfilingConfig', (_message.Message,), dict(
  DESCRIPTOR = _PROFILINGCONFIG,
  __module__ = 'perfprofd_config_pb2'
  # @@protoc_insertion_point(class_scope:android.perfprofd.ProfilingConfig)
  ))
_sym_db.RegisterMessage(ProfilingConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021android.perfprofdH\003'))
# @@protoc_insertion_point(module_scope)
