# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perf_profile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='perf_profile.proto',
  package='wireless_android_play_playlog',
  syntax='proto2',
  serialized_pb=_b('\n\x12perf_profile.proto\x12\x1dwireless_android_play_playlog\"G\n\rAddressSample\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x03(\x04\x12\x16\n\x0eload_module_id\x18\x02 \x03(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x03\"D\n\x0bRangeSample\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x04\x12\n\n\x02to\x18\x03 \x01(\x04\x12\r\n\x05\x63ount\x18\x04 \x01(\x03\",\n\nLoadModule\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x62uild_id\x18\x02 \x01(\t\"\xb5\x01\n\x11LoadModuleSamples\x12\x16\n\x0eload_module_id\x18\x01 \x01(\x05\x12\x45\n\x0f\x61\x64\x64ress_samples\x18\x02 \x03(\x0b\x32,.wireless_android_play_playlog.AddressSample\x12\x41\n\rrange_samples\x18\x03 \x03(\x0b\x32*.wireless_android_play_playlog.RangeSample\"a\n\x0eProgramSamples\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x41\n\x07modules\x18\x02 \x03(\x0b\x32\x30.wireless_android_play_playlog.LoadModuleSamples\"\xa0\x03\n\x12\x41ndroidPerfProfile\x12J\n\x05\x65vent\x18\x01 \x01(\x0e\x32;.wireless_android_play_playlog.AndroidPerfProfile.EventType\x12\x15\n\rtotal_samples\x18\x02 \x01(\x03\x12?\n\x08programs\x18\x03 \x03(\x0b\x32-.wireless_android_play_playlog.ProgramSamples\x12?\n\x0cload_modules\x18\x04 \x03(\x0b\x32).wireless_android_play_playlog.LoadModule\x12\x12\n\ndisplay_on\x18\x05 \x01(\x08\x12\x18\n\x10sys_load_average\x18\x06 \x01(\x05\x12\x15\n\rcamera_active\x18\x07 \x01(\x08\x12\x0f\n\x07\x62ooting\x18\x08 \x01(\x08\x12\x12\n\non_charger\x18\t \x01(\x08\x12\x17\n\x0f\x63pu_utilization\x18\n \x01(\x05\"\"\n\tEventType\x12\t\n\x05\x43YCLE\x10\x00\x12\n\n\x06\x42RANCH\x10\x01\x42\x1d\n\x19\x63om.google.common.loggingH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ANDROIDPERFPROFILE_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='wireless_android_play_playlog.AndroidPerfProfile.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CYCLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BRANCH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=908,
  serialized_end=942,
)
_sym_db.RegisterEnumDescriptor(_ANDROIDPERFPROFILE_EVENTTYPE)


_ADDRESSSAMPLE = _descriptor.Descriptor(
  name='AddressSample',
  full_name='wireless_android_play_playlog.AddressSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='wireless_android_play_playlog.AddressSample.address', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_module_id', full_name='wireless_android_play_playlog.AddressSample.load_module_id', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='wireless_android_play_playlog.AddressSample.count', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=124,
)


_RANGESAMPLE = _descriptor.Descriptor(
  name='RangeSample',
  full_name='wireless_android_play_playlog.RangeSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='wireless_android_play_playlog.RangeSample.start', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='wireless_android_play_playlog.RangeSample.end', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='wireless_android_play_playlog.RangeSample.to', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='wireless_android_play_playlog.RangeSample.count', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=194,
)


_LOADMODULE = _descriptor.Descriptor(
  name='LoadModule',
  full_name='wireless_android_play_playlog.LoadModule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='wireless_android_play_playlog.LoadModule.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build_id', full_name='wireless_android_play_playlog.LoadModule.build_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=240,
)


_LOADMODULESAMPLES = _descriptor.Descriptor(
  name='LoadModuleSamples',
  full_name='wireless_android_play_playlog.LoadModuleSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='load_module_id', full_name='wireless_android_play_playlog.LoadModuleSamples.load_module_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_samples', full_name='wireless_android_play_playlog.LoadModuleSamples.address_samples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range_samples', full_name='wireless_android_play_playlog.LoadModuleSamples.range_samples', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=424,
)


_PROGRAMSAMPLES = _descriptor.Descriptor(
  name='ProgramSamples',
  full_name='wireless_android_play_playlog.ProgramSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='wireless_android_play_playlog.ProgramSamples.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modules', full_name='wireless_android_play_playlog.ProgramSamples.modules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=523,
)


_ANDROIDPERFPROFILE = _descriptor.Descriptor(
  name='AndroidPerfProfile',
  full_name='wireless_android_play_playlog.AndroidPerfProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='wireless_android_play_playlog.AndroidPerfProfile.event', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_samples', full_name='wireless_android_play_playlog.AndroidPerfProfile.total_samples', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='programs', full_name='wireless_android_play_playlog.AndroidPerfProfile.programs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_modules', full_name='wireless_android_play_playlog.AndroidPerfProfile.load_modules', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='display_on', full_name='wireless_android_play_playlog.AndroidPerfProfile.display_on', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sys_load_average', full_name='wireless_android_play_playlog.AndroidPerfProfile.sys_load_average', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='camera_active', full_name='wireless_android_play_playlog.AndroidPerfProfile.camera_active', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='booting', full_name='wireless_android_play_playlog.AndroidPerfProfile.booting', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='on_charger', full_name='wireless_android_play_playlog.AndroidPerfProfile.on_charger', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu_utilization', full_name='wireless_android_play_playlog.AndroidPerfProfile.cpu_utilization', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ANDROIDPERFPROFILE_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=942,
)

_LOADMODULESAMPLES.fields_by_name['address_samples'].message_type = _ADDRESSSAMPLE
_LOADMODULESAMPLES.fields_by_name['range_samples'].message_type = _RANGESAMPLE
_PROGRAMSAMPLES.fields_by_name['modules'].message_type = _LOADMODULESAMPLES
_ANDROIDPERFPROFILE.fields_by_name['event'].enum_type = _ANDROIDPERFPROFILE_EVENTTYPE
_ANDROIDPERFPROFILE.fields_by_name['programs'].message_type = _PROGRAMSAMPLES
_ANDROIDPERFPROFILE.fields_by_name['load_modules'].message_type = _LOADMODULE
_ANDROIDPERFPROFILE_EVENTTYPE.containing_type = _ANDROIDPERFPROFILE
DESCRIPTOR.message_types_by_name['AddressSample'] = _ADDRESSSAMPLE
DESCRIPTOR.message_types_by_name['RangeSample'] = _RANGESAMPLE
DESCRIPTOR.message_types_by_name['LoadModule'] = _LOADMODULE
DESCRIPTOR.message_types_by_name['LoadModuleSamples'] = _LOADMODULESAMPLES
DESCRIPTOR.message_types_by_name['ProgramSamples'] = _PROGRAMSAMPLES
DESCRIPTOR.message_types_by_name['AndroidPerfProfile'] = _ANDROIDPERFPROFILE

AddressSample = _reflection.GeneratedProtocolMessageType('AddressSample', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSSAMPLE,
  __module__ = 'perf_profile_pb2'
  # @@protoc_insertion_point(class_scope:wireless_android_play_playlog.AddressSample)
  ))
_sym_db.RegisterMessage(AddressSample)

RangeSample = _reflection.GeneratedProtocolMessageType('RangeSample', (_message.Message,), dict(
  DESCRIPTOR = _RANGESAMPLE,
  __module__ = 'perf_profile_pb2'
  # @@protoc_insertion_point(class_scope:wireless_android_play_playlog.RangeSample)
  ))
_sym_db.RegisterMessage(RangeSample)

LoadModule = _reflection.GeneratedProtocolMessageType('LoadModule', (_message.Message,), dict(
  DESCRIPTOR = _LOADMODULE,
  __module__ = 'perf_profile_pb2'
  # @@protoc_insertion_point(class_scope:wireless_android_play_playlog.LoadModule)
  ))
_sym_db.RegisterMessage(LoadModule)

LoadModuleSamples = _reflection.GeneratedProtocolMessageType('LoadModuleSamples', (_message.Message,), dict(
  DESCRIPTOR = _LOADMODULESAMPLES,
  __module__ = 'perf_profile_pb2'
  # @@protoc_insertion_point(class_scope:wireless_android_play_playlog.LoadModuleSamples)
  ))
_sym_db.RegisterMessage(LoadModuleSamples)

ProgramSamples = _reflection.GeneratedProtocolMessageType('ProgramSamples', (_message.Message,), dict(
  DESCRIPTOR = _PROGRAMSAMPLES,
  __module__ = 'perf_profile_pb2'
  # @@protoc_insertion_point(class_scope:wireless_android_play_playlog.ProgramSamples)
  ))
_sym_db.RegisterMessage(ProgramSamples)

AndroidPerfProfile = _reflection.GeneratedProtocolMessageType('AndroidPerfProfile', (_message.Message,), dict(
  DESCRIPTOR = _ANDROIDPERFPROFILE,
  __module__ = 'perf_profile_pb2'
  # @@protoc_insertion_point(class_scope:wireless_android_play_playlog.AndroidPerfProfile)
  ))
_sym_db.RegisterMessage(AndroidPerfProfile)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.google.common.loggingH\003'))
# @@protoc_insertion_point(module_scope)
